###
### Liquibase version: 4.30.0+
###
### Liquibase sales: https://www.liquibase.com/contact-us
### Liquibase support: https://support.liquibase.com
###

###
### Flow documentation: https://docs.liquibase.com/commands/flow/flow.html
###

###
### Global variables used in the flowfile
###
globalVariables:
  LB_BASE_DIR: "${LB_BASE_DIR:-.}"
  LB_ENVIRONMENT: "${LB_ENVIRONMENT:-DEV}"
  DEV_URL: "${DEV_URL:-jdbc:snowflake://ba89345.us-east-2.aws.snowflakecomputing.com/?warehouse=CUSTOMERSUCCESS_WH&db=AMDB_DEV&schema=DBT&user=adeelmalik}"
  PROD_URL: "${PROD_URL:-jdbc:snowflake://ba89345.us-east-2.aws.snowflakecomputing.com/?warehouse=CUSTOMERSUCCESS_WH&db=AMDB&schema=DBT&user=adeelmalik}"

###
### Stages to execute
###
stages:
  Remove_Folders:
    actions:
      #
      # Rollback last updates
      #
      # - type: liquibase
      #   command: rollback-count
      #   globalArgs: { reports-enabled: "false" }
      #   cmdArgs: { count: "6" }
      #
      # Remove files
      #
      - type: shell
        command: rm -rf reports snapshots ../target

  Reset_DEV:
    actions:
      # - type: liquibase
      #   command: execute-sql
      #   cmdArgs: { url: "${DEV_URL}", sql: "drop table amdb_dev.dbt.DATABASECHANGELOGHISTORY"}
      #   globalArgs: {dbclhistory-enabled: "false"}

      - type: liquibase
        command: dropall
        cmdArgs: { url: "${DEV_URL}" }
        globalArgs: {dbclhistory-enabled: "false"}

  Reset_PROD:
    actions:
      # - type: liquibase
      #   command: execute-sql
      #   cmdArgs: { url: "${PROD_URL}", sql: "drop table amdb.dbt.DATABASECHANGELOGHISTORY"}
      #   globalArgs: {dbclhistory-enabled: "false"}

      - type: liquibase
        command: dropall
        cmdArgs: { url: "${PROD_URL}" }
        globalArgs: {dbclhistory-enabled: "false"}


###
### Always execute
###
endStage:
  actions:
    - type: liquibase
      command: history
      cmdArgs: { url: "${DEV_URL}" }

    - type: liquibase
      command: history
      cmdArgs: { url: "${PROD_URL}" }
