liquibase_dev:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: BA89345.us-east-2.aws
      user: adeelmalik
      role: LIQUIBASE_USER
      database: AMDB_DEV
      warehouse: CUSTOMERSUCCESS_WH
      schema: DBT
      threads: 4
      client_session_keep_alive: False
      private_key_path: /Users/adeelmalik/adeelmalik.p8
      private_key_passphrase: "1234"

